# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - jc-application-site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          cache: "npm"

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
      
      - name: Prune dev dependencies
        run: npm prune --omit=dev

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            build
            drizzle
            package.json
            package-lock.json
            node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_47F26A9E94314D36B5C949A4D57DA453 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9662C0D0BBD24EF7B48485186F7F98CC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_293144000C9C4A22AE067D352AC9E577 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jc-application-site'
          slot-name: 'Production'
          package: .
          